### ISSUE TITLE
Playing stop when opening the upload box

### ISSUE THREAD

**Issue by bebatut** [TailorDev/galaxy-tourbuilder#14]
Hi,

When testing a tour, the playing stops when the upload box should open. But it works for the same tour installed on a running Galaxy instance.
I got this error on both Chrome and Firefox, with several tours (e.g. https://raw.githubusercontent.com/galaxyproject/training-material/master/topics/metagenomics/tutorials/general-tutorial/tours/metagenomics-general-tutorial-amplicon.yml).

Bérénice

**Comment by willdurand** [comment]
Have you ever successfully run a tour involving an upload box?

**Comment by bebatut** [comment]
Yes for Tool installed on a Galaxy instance but not using the extension

**Comment by willdurand** [comment]
Could you create a tour (YAML content) with the minimal number of steps to trigger the bug? Including a step that cannot be reached because of the error.

Do you see anything in the console (dev tools)?

**Comment by bebatut** [comment]
Minimal tour: 

```
id: new-tour
name: Galaxy Tour
description: This is a new tour created with the Galaxy Tour Builder extension.
title_default: Galaxy Tour
steps:
  - title: Step 1
    element: '#tool-panel-upload-button .fa.fa-upload'
    content: ''
    placement: right
    postclick:
      - '#tool-panel-upload-button .fa.fa-upload'
      - '#btn-reset'
  - title: Step 2
    element: '#btn-close'
    content: ''
    placement: left
```

What is happening

![jun-24-2018 05-16-13](https://user-images.githubusercontent.com/1842467/41815517-d5870664-776d-11e8-8ba4-27c3fdae4890.gif)

Upload box is not opening - Error in the console:

![screen shot 2018-06-24 at 05 19 14](https://user-images.githubusercontent.com/1842467/41815527-33b92d5c-776e-11e8-9383-c466ceabbf31.png)
